// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH44z8SebFqxrjgQ_EVKPjz2-OHArTeJU',
    appId: '1:440811087597:web:f96ea8f57ae272a46fcee4',
    messagingSenderId: '440811087597',
    projectId: 'autolink-lanka',
    authDomain: 'autolink-lanka.firebaseapp.com',
    storageBucket: 'autolink-lanka.firebasestorage.app',
    measurementId: 'G-BV7ZZ0Y33Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt6E9WUwffcp0Uc-CLRgP13cJSmKWStms',
    appId: '1:440811087597:android:62929a36bf9dfcfa6fcee4',
    messagingSenderId: '440811087597',
    projectId: 'autolink-lanka',
    storageBucket: 'autolink-lanka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCYrR0QfY6u6ArziJNlvYiZn8pP4ZWw3g',
    appId: '1:440811087597:ios:2b9ccdab8962a9eb6fcee4',
    messagingSenderId: '440811087597',
    projectId: 'autolink-lanka',
    storageBucket: 'autolink-lanka.firebasestorage.app',
    iosBundleId: 'com.example.autolinkLanka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCYrR0QfY6u6ArziJNlvYiZn8pP4ZWw3g',
    appId: '1:440811087597:ios:2b9ccdab8962a9eb6fcee4',
    messagingSenderId: '440811087597',
    projectId: 'autolink-lanka',
    storageBucket: 'autolink-lanka.firebasestorage.app',
    iosBundleId: 'com.example.autolinkLanka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH44z8SebFqxrjgQ_EVKPjz2-OHArTeJU',
    appId: '1:440811087597:web:e2c19ba9c18f32316fcee4',
    messagingSenderId: '440811087597',
    projectId: 'autolink-lanka',
    authDomain: 'autolink-lanka.firebaseapp.com',
    storageBucket: 'autolink-lanka.firebasestorage.app',
    measurementId: 'G-68JCQV3ND8',
  );
}
